services:
  app:
    build: 
      context: .
      target: dev
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      - sqlserver
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge